services:
  db:
    image: postgres:15
    container_name: sgt_dia_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: sped_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    container_name: sgt_dia_backend
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/sped_db
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./backend-app:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    container_name: sgt_dia_frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
  backend_node_modules: