import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15, 23, 42, 0.6)' },
  sheetContainer: { backgroundColor: '#ffffff', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingTop: 12, maxHeight: '90%' },
  dragHandle: { width: 40, height: 4, backgroundColor: '#cbd5e1', borderRadius: 2, alignSelf: 'center', marginBottom: 16 },
  scrollContent: { paddingHorizontal: 24, paddingBottom: 24 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  iconContainer: { backgroundColor: '#eff6ff', padding: 10, borderRadius: 12 },
  headerTexts: { justifyContent: 'center' },
  title: { fontSize: 18, fontWeight: 'bold', color: '#0f172a' },
  subtitle: { fontSize: 14, color: '#64748b', marginTop: 2 },
  closeButton: { backgroundColor: '#f1f5f9', padding: 8, borderRadius: 20 },
  contextContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f8fafc', padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#e2e8f0', marginBottom: 24, gap: 8 },
  contextText: { fontSize: 15, color: '#334155', fontWeight: '500' },
  inputGroup: { marginBottom: 24 },
  label: { fontSize: 14, fontWeight: '600', color: '#0f172a', marginBottom: 8 },
  required: { color: '#ef4444' },
  textAreaContainer: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 12, backgroundColor: '#ffffff', padding: 12, minHeight: 120 },
  textArea: { flex: 1, fontSize: 16, color: '#334155' },
  charCount: { textAlign: 'right', fontSize: 12, color: '#94a3b8', marginTop: 8 },
  helperRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 6 },
  helperText: { fontSize: 12, color: '#94a3b8' },
  photoPickerButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#eff6ff', borderWidth: 1, borderColor: '#bfdbfe', borderRadius: 12, padding: 16 },
  photoPickerIconArea: { backgroundColor: '#ffffff', padding: 10, borderRadius: 10, marginRight: 12 },
  photoPickerTexts: { flex: 1 },
  photoPickerTitle: { fontSize: 15, fontWeight: '600', color: '#1d4ed8' },
  photoPickerSubtitle: { fontSize: 13, color: '#64748b', marginTop: 2 },
  photoPreviewContainer: { alignItems: 'center', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, padding: 16, backgroundColor: '#f8fafc' },
  photoPreview: { width: '100%', height: 200, borderRadius: 8, marginBottom: 12 },
  removePhotoButton: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  removePhotoText: { color: '#ef4444', fontWeight: '500' },
  footer: { padding: 24, paddingTop: 16, borderTopWidth: 1, borderTopColor: '#e2e8f0', backgroundColor: '#ffffff' },
  saveButton: { backgroundColor: '#2563eb', paddingVertical: 16, borderRadius: 12, alignItems: 'center' },
  saveButtonDisabled: { backgroundColor: '#94a3b8' },
  saveButtonText: { color: '#ffffff', fontSize: 16, fontWeight: 'bold' },
});